# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x65vice.proto\x12\x06\x64\x65vice\"~\n\x06\x44\x65vice\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x62rand\x18\x03 \x01(\t\x12\r\n\x05model\x18\x04 \x01(\t\x12\n\n\x02os\x18\x05 \x01(\t\x12\x0f\n\x07version\x18\x06 \x01(\t\x12\x0c\n\x04wifi\x18\x07 \x01(\x08\x12\x11\n\tbluetooth\x18\x08 \x01(\x08\"\"\n\x14GetDeviceByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x16\n\x14GetAllDevicesRequest\"5\n\x12\x41llDevicesResponse\x12\x1f\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x0e.device.Device\"2\n\x10\x41\x64\x64\x44\x65viceRequest\x12\x1e\n\x06\x64\x65vice\x18\x01 \x01(\x0b\x32\x0e.device.Device\"A\n\x13UpdateDeviceRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x1e\n\x06\x64\x65vice\x18\x02 \x01(\x0b\x32\x0e.device.Device\"!\n\x13\x44\x65leteDeviceRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\'\n\x14\x44\x65leteDeviceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xd8\x02\n\rDeviceService\x12=\n\rGetDeviceById\x12\x1c.device.GetDeviceByIdRequest\x1a\x0e.device.Device\x12I\n\rGetAllDevices\x12\x1c.device.GetAllDevicesRequest\x1a\x1a.device.AllDevicesResponse\x12\x35\n\tAddDevice\x12\x18.device.AddDeviceRequest\x1a\x0e.device.Device\x12;\n\x0cUpdateDevice\x12\x1b.device.UpdateDeviceRequest\x1a\x0e.device.Device\x12I\n\x0c\x44\x65leteDevice\x12\x1b.device.DeleteDeviceRequest\x1a\x1c.device.DeleteDeviceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DEVICE']._serialized_start=24
  _globals['_DEVICE']._serialized_end=150
  _globals['_GETDEVICEBYIDREQUEST']._serialized_start=152
  _globals['_GETDEVICEBYIDREQUEST']._serialized_end=186
  _globals['_GETALLDEVICESREQUEST']._serialized_start=188
  _globals['_GETALLDEVICESREQUEST']._serialized_end=210
  _globals['_ALLDEVICESRESPONSE']._serialized_start=212
  _globals['_ALLDEVICESRESPONSE']._serialized_end=265
  _globals['_ADDDEVICEREQUEST']._serialized_start=267
  _globals['_ADDDEVICEREQUEST']._serialized_end=317
  _globals['_UPDATEDEVICEREQUEST']._serialized_start=319
  _globals['_UPDATEDEVICEREQUEST']._serialized_end=384
  _globals['_DELETEDEVICEREQUEST']._serialized_start=386
  _globals['_DELETEDEVICEREQUEST']._serialized_end=419
  _globals['_DELETEDEVICERESPONSE']._serialized_start=421
  _globals['_DELETEDEVICERESPONSE']._serialized_end=460
  _globals['_DEVICESERVICE']._serialized_start=463
  _globals['_DEVICESERVICE']._serialized_end=807
# @@protoc_insertion_point(module_scope)
